backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: "https://vitoosh.github.io/vitooshartwork"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "images"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "text", required: false }

  - name: "profile"
    label: "Profile"
    files:
      - file: "profile.json"
        label: "Profile Info"
        name: "profile"
        fields:
          - { name: "name", label: "Name", widget: "string", default: "VITOOSH" }
          - { name: "bio", label: "Bio", widget: "text" }
          - { name: "email", label: "Email", widget: "string" }
