backend:
  name: github
  repo: vitoosh/vitooshartwork  # your repo
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: "https://vitooshartwork.vercel.app"
display_url: "https://vitooshartwork.vercel.app"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.html"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Profile Image", name: "profile", widget: "image" }
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "content/contact.html"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Message", name: "message", widget: "text" }
