backend:
  name: git-gateway
  branch: main  # or 'master' if that’s your default branch

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://vitoosh.netlify.app"
display_url: "https://vitoosh.netlify.app"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "artworks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
