backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

# Artworks: stored as a JSON list in artworks.json (image-only entries)
collections:
  - name: "artworks"
    label: "Artworks"
    file: "artworks.json"
    format: json
    fields:
      - label: "Images"
        name: "artworks"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"

  - name: "about"
    label: "About Page"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Profile image", name: "image", widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "contact"
    label: "Contact Page"
    files:
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
