backend:
  name: github
  repo: vitoosh/vitooshartwork
  branch: main
  auth_type: implicit
  app_id: Ov23lirezaJGlttcQrRl

media_folder: "images"
public_folder: "/images"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
