backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artworks"
    label: "Artworks"
    file: "artworks.json"
    format: json
    fields:
      - label: "Images"
        name: "artworks"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
